FROM node:16-alpine AS builder

# Рабочая директория
WORKDIR /app

# Копируем зависимости
COPY package*.json ./
RUN npm ci

# Копируем код
COPY . .

# Установка PM2 глобально
RUN npm install -g pm2

# Сборка
RUN npm run build

# Запуск билда
CMD ["pm2-runtime", "ecosystem.config.js"]

# second stage
FROM node:16-alpine AS production

WORKDIR /app/

# С помощью параметера --from указываем, что копировать нужно из образа builder
# Копируем package.json и package-lock.json (потребуются для установки зависимостей)
COPY --from=builder /app/package*.json ./

# Устанавливаем только зависимости, необходимые в продакшене
# --omit=dev означает «пропустить dev-зависимости»
RUN npm i --production --omit=dev --no-audit --no-fund \
        && npm i -g pm2

# Копируем директорию со сборкой приложения
COPY --from=builder /app/dist ./dist/

# COPY ./ecosystem/config.js ./

# Экспорт порта из .env
# ENV PORT=$PORT_BACKEND
# EXPOSE $PORT

# Указываем команду для запуска приложения
ENTRYPOINT ["pm2-runtime","start", "ecosystem.config.js"]
